services:
  backend:
    build: 
      context: ./backend
    container_name: "friends_backend"
    networks:
      - friends_intranet
    environment:
      - MONGO_URI=${MONGO_URI}
      - JWT_SECRET=${JWT_SECRET}

  frontend:
    build: 
      context: ./frontend
    container_name: "friends_frontend"
    environment:
      - VITE_API_URL=${VITE_API_URL}
    networks:
      - friends_intranet
    depends_on:
      - backend
    
  reverse_proxy:
    image: nginx:alpine
    networks:
      - friends_intranet
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    port:
      - "80:80"
    depends_on:
      - frontend

networks:
  friends_intranet:
