name: Friends CI/CD Pipeline

on:
  push:
    branches: [master]

env:
  DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
  EC2_IP: ${{ secrets.EC2_IP }}
  SSH_KEY: ${{ secrets.SSH_KEY }}

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push backend
        uses: docker/build-push-action@v4
        with:
          context: ./backend
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/friends-backend:latest
          push: true

      - name: Build and push frontend
        uses: docker/build-push-action@v4
        with:
          context: ./frontend
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/friends-frontend:latest
          push: true

      - name: Deploy to EC2
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.EC2_IP }}
          key: ${{ secrets.SSH_KEY }}
          username: ubuntu
          script: |
            # Clone 
            git clone https://github.com/BeBAKE/Friends.git || true
            cd Friends
            git pull origin master

            # Stopping existing containers
            docker-compose down

            # Pulling latest images
            docker pull ${{ secrets.DOCKERHUB_USERNAME }}/friends-backend:latest
            docker pull ${{ secrets.DOCKERHUB_USERNAME }}/friends-frontend:latest

            MONGO_URI=${{ secrets.MONGO_URI }} 
            JWT_SECRET=${{ secrets.JWT_SECRET }} 
            VITE_API_URL=${{ secrets.VITE_API_URL }}

            docker-compose up -d
