name: Friends CI/CD Pipeline

on:
  push:
    branches: [master]

env:
  DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
  EC2_IP: ${{ secrets.EC2_IP }}
  SSH_KEY: ${{ secrets.SSH_KEY }}

jobs:
  build-and-deploy-backend:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push backend
        uses: docker/build-push-action@v4
        with:
          context: ./backend
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/friends-backend:latest
          push: true

      - name: Deploy to EC2
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: ${{ secrets.EC2_IP }}
          key: ${{ secrets.SSH_KEY }}
          username: ubuntu
          script: |
            # Clone 
            git clone https://github.com/BeBAKE/Friends.git || true
            cd ~/Friends
            git pull origin master

            echo MONGO_URI="${{ secrets.MONGO_URI }}" > .env
            echo JWT_SECRET="${{ secrets.JWT_SECRET }}" >> .env
            echo DOCKERHUB_USERNAME="${{ secrets.DOCKERHUB_USERNAME }}" >> .env

            # Stopping existing containers
            sudo docker compose down

            # Pulling latest images
            sudo docker pull ${{ secrets.DOCKERHUB_USERNAME }}/friends-backend:latest

            sudo docker compose up -d
        env:
          MONGO_URI: ${{ secrets.MONGO_URI }}
          JWT_SECRET: ${{ secrets.JWT_SECRET }}
          DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}

  deploy-frontend:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      deployments: write
    needs: build-and-deploy-backend
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install
        working-directory: ./frontend

      - name: Build React app with environment variable
        run: |
          echo VITE_API_URL="${{ secrets.VITE_API_URL }}" > .env
          npm run build
        working-directory: ./frontend
        env:
          VITE_API_URL: ${{ secrets.VITE_API_URL }}

      - name: Publish to Cloudflare Pages
        uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          projectName: friends-frontend
          preCommands: ls -lart
          directory: dist
          gitHubToken: ${{ secrets.GITHUB_TOKEN }}
